### ISSUE TITLE
Suggestion: Time windows for calculation of regions of interest

### ISSUE THREAD

**Issue by phockett** [jonathanunderwood/limapack#1]
Currently time-steps (as I understand it) are defined in the input file from tstart to tend, in tn steps.  This range must span the laser pulse duration.  For regions of interested far from t0, e.g. 1/2 revival, this results in unnecessarily long calculations as all time-steps between t0 and tx must be calculated, and this becomes even worse if high temporal resolution results are sought.

A nice addition would therefore be a way to choose the time-window of the outputs independently of the TDSE time-window (i.e. independently of the laser pulse).  This could be via an additional, optional set of inputs, e.g. {t1,t2,tn; t3,t4,tn;...}, where tx specify start and end times of interest, with tn steps between, and one could specify several different regions of interest.  

Optionally, this could also replace the current tstart/tstop definition with the TDSE region instead being chosen automatically to match the input laser pulse parameters, depending on whether one wishes to retain transparent user control over this parameter or not.

**Comment by jonathanunderwood** [comment]
This is now implemented (but mostly untested).
